docs/parsers/html.md
docs/parsers/jsx.md
docs/parsers/svelte.md
docs/parsers/vue.md

Thank you for taking your time to create this plugin, I really appreciated.
Love the project!! 😍
Just fix the example usage on Flat config.
without `.rules` linter will throw an error.

docs(typo): add .rules to flat config

---

src/parsers/svelte.ts
src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts
src/rules/tailwind-no-unnecessary-whitespace.test.ts
src/rules/tailwind-no-unnecessary-whitespace.ts

Example:
```tsx
// BAD
<div class="
" />
```
```tsx
// GOOD
<div class="" />
```

fix: don't wrap empty attributes

---

src/rules/tailwind-no-unnecessary-whitespace.test.ts
src/rules/tailwind-no-unnecessary-whitespace.ts

Example:
```tsx
// BAD
<div·class="
··a··
··b··
"·/>
```
```tsx
// GOOD
<div·class="
··a
··b
"·/>
```

fix: remove unnecessary trailing spaces in multiline strings

---

docs/rules/multiline.md
src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts

fix: false positives when using `crlf`

---

src/rules/tailwind-sort-classes.ts

when using `.ts` config or when linting specific nested directory

fix: resolving tailwind config

---

.vscode/extensions.json
eslint.config.js
src/rules/tailwind-multiline.test.ts
src/rules/tailwind-no-unnecessary-whitespace.test.ts
src/rules/tailwind-sort-classes.test.ts
tests/utils.ts

- use vitest directly
- allow template literals to avoid unnecessary escaping in most cases and possibly in the future add syntax highlighting
- simplify jsx tests
- use valid html element that is self closing

test: simplify testing

---

src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts

Before:
```tsx
${true}a
`} />
```
After:
```tsx
${true}a
`} />
```

fix: remove unnecessary newline after single sticky class

---

src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts

Fixes invalid quotes when arrays get wrapped.
```tsx
// invalid
a b c
d e f
"]} />
```
```tsx
// valid
a b c
d e f
`]} />
```

fix: change quotes in multiline arrays

---

src/rules/tailwind-multiline.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts
src/utils/quotes.test.ts
src/utils/quotes.ts

Escapes nested quotes
```tsx
// invalid
```
```tsx
// valid
```

fix: escape nested quotes

---

src/parsers/es.ts
src/utils/matchers.test.ts

Call expression matcher will now override classAttributes matcher:
```tsx
```
```ts
{
callees: [["defined", [{ match: MatcherType.String }]]],
classAttributes: [["class", [{ match: MatcherType.ObjectValue }]]]
}
```
When using these options, it will now use the `callees` matcher instead of the `classAttributes` matcher

fix: allow call expressions as object values

---

src/parsers/jsx.ts
src/parsers/svelte.ts
src/parsers/vue.ts

Attributes in html are case insensitive so they should here as well.

fix: attributes are no longer case sensitive

---

docs/api/defaults.md
docs/rules/multiline.md
docs/rules/no-unnecessary-whitespace.md
docs/rules/sort-classes.md
src/config/default-config.ts
src/parsers/html.ts
src/rules/tailwind-multiline.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts

Matchers are not compatible with the HTML parser.
This PR adds a `name` attribute for `class` to the defaults and warns if someone tries to use matchers with the html parser.

fix: warn in html matchers

---

src/configs/config.ts

Removes plugin definition in shared config which throws an error when used in flat config.
The plugin definition is actually not necessary in the config as the plugin must already be included to be able to use the config.
fixes #41

fix: remove unnecessary plugin import in shared config

---

src/parsers/svelte.test.ts
src/parsers/svelte.ts

Adds support for svelte attribute shorthand syntax. Fixes #42 
Example: 
```svelte
<script> 
let shorthandAttribute = "shorthand attributes throw an error"; 
</script>
<button
class="flex bg-red-500"
{shorthandAttribute}
/>
```

fix: support svelte shorthand syntax

---

src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts

Possible fix for #52 
Fixes [group](https://github.com/schoero/eslint-plugin-readable-tailwind/blob/main/docs/rules/multiline.md#options)  type `never` in combination with template literal expressions.

fix: group type never not working with expressions

---

docs/rules/multiline.md
src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts

Prefer a single line for different modifiers/variants. When set to `true`, the rule will keep all modifiers/variants on a single line until the line exceeds the `printWidth` or `classesPerLine` limit.
```tsx
// ❌ BAD
<div class="text-black underline focus:font-bold focus:text-opacity-70 hover:font-bold hover:text-opacity-70" />;
```
```tsx
// ✅ GOOD: with { preferSingleLine: true, printWidth: 120 }
<div class="text-black underline focus:font-bold focus:text-opacity-70 hover:font-bold hover:text-opacity-70" />;
```
```tsx
// ✅ GOOD: with { preferSingleLine: true, printWidth: 80 }
<div class={`
text-black underline
focus:font-bold focus:text-opacity-70
hover:font-bold hover:text-opacity-70
`} />;
```
closes #50

feat: new option `preferSingleLine`

---

docs/rules/multiline.md
docs/rules/no-duplicate-classes.md
docs/rules/sort-classes.md
docs/settings/settings.md
src/rules/tailwind-multiline.ts
src/rules/tailwind-no-duplicate-classes.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts
src/types/rule.ts
tests/unit/settings.test.ts
tests/utils.ts

Adds support for the settings object to globally configure shared options across all rules. 
```jsonc
{
"plugins": { /* ... */ },
"rules": { /* ... */ },
"settings": {
"readable-tailwind": {
"classAttributes": ["class", "className"],
"callees": ["cc", "clb", "clsx", "cn", "cnb", "ctl", "cva", "cx", "dcnb", "objstr", "tv", "twJoin", "twMerge"],
"variables": ["className", "classNames", "classes", "style", "styles"]
}
}
}
```

feat: settings

---

src/rules/tailwind-multiline.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts
src/utils/utils.ts

Displays the current class string and the fixed class string in the linting error message.
```
Incorrect line wrapping. Expected
`flex·items-center·p-6·max-xl:mb-2·max-xl:mt-8·xl:-ml-36·xl:self-start↵`
to be
`↵
··flex·items-center·p-6↵
↵
··max-xl:mb-2·max-xl:mt-8↵
↵
··xl:-ml-36·xl:self-start↵
`
```

refactor: improve display of linting errors

---

src/rules/tailwind-multiline.ts

when lines wrap on two lines immediately but was the theoretically short enough to not wrap.
```tsx
const Command = React.forwardRef<
React.ElementRef<typeof CommandPrimitive>,
React.ComponentPropsWithoutRef<typeof CommandPrimitive>
>(({ className, ...props }, ref) => (
<CommandPrimitive
className={cn(
`flex size-full flex-col overflow-hidden rounded-md bg-popover text-popover-foreground`,
className
)}
ref={ref}
{...props}
/>
))
```
was wrapped to 
```tsx
const Command = React.forwardRef<
React.ElementRef<typeof CommandPrimitive>,
React.ComponentPropsWithoutRef<typeof CommandPrimitive>
>(({ className, ...props }, ref) => (
<CommandPrimitive
className={cn(
`
flex size-full flex-col overflow-hidden rounded-md bg-popover
text-popover-foreground
`,
className
)}
ref={ref}
{...props}
/>
))
``` …

fix: fixing loop

---

docs/api/defaults.md
docs/rules/multiline.md
docs/rules/no-duplicate-classes.md
docs/rules/no-unnecessary-whitespace.md
docs/rules/sort-classes.md
docs/settings/settings.md
src/api/defaults.ts
src/options/default-options.ts
src/options/descriptions.ts
src/parsers/es.ts
src/rules/tailwind-multiline.test.ts
src/rules/tailwind-multiline.ts
src/rules/tailwind-no-duplicate-classes.test.ts
src/rules/tailwind-no-duplicate-classes.ts
src/rules/tailwind-no-unnecessary-whitespace.test.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.test.ts
src/rules/tailwind-sort-classes.ts
src/types/rule.ts
src/utils/matchers.test.ts
src/utils/matchers.ts
src/utils/regex.test.ts

Adds support for tagged template literals. Closes #64 
```tsx
const styles = tw`this will get linted`;
```
This PR does not change the default settings, so no tags will get linted out of the box.
To lint tagged template literals, the best way is to use the [strings matcher](https://github.com/schoero/eslint-plugin-readable-tailwind/blob/main/docs/concepts/concepts.md#types-of-matchers) to ensure that nested expressions will get linted correctly.
```ts
{
//...
options: [{ 
tags: [
[
"tw", [{ match: MatcherType.String }]
]
]
}]
}
```
```tsx
const styles = tw`
this string will get linted
${
someVar === "this string will NOT get linted" 
? "this string will get linted"
: "this string will get linted"
}
this string will get linted
`;
```

feat: template literal tags

---

docs/concepts/concepts.md
src/parsers/es.test.ts
src/parsers/es.ts
src/parsers/jsx.ts
src/parsers/svelte.ts
src/parsers/vue.test.ts
src/parsers/vue.ts
src/utils/matchers.test.ts
src/utils/utils.ts

Add regular expression support for variable, callee and attribute names.
```ts
// with option { variables: ["^.*Styles$"] }
const buttonStyles = "will be linted";
const buttonClasses = "will NOT be linted";
```
fixes #62

feat!: regex names

---

src/rules/tailwind-multiline.ts
src/rules/tailwind-no-duplicate-classes.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts

Fixes an issue that rule options did not override [settings](https://github.com/schoero/eslint-plugin-readable-tailwind/blob/main/docs/settings/settings.md#settings).
```jsonc
{
// rule options
rules: {
"eslint-plugin-readable-tailwind/no-unnecessary-whitespace": ["warn", {
/* should override settings below */
}]
},
// plugin settings
settings: {
"eslint-plugin-readable-tailwind": {
/* should get overwritten */
}
}
}
```

fix: override settings

---

src/options/default-options.ts

Adds  `className` to the default  attribute names.
The `className` matcher does not work because the whole JSX expression is inside an object.
https://github.com/schoero/eslint-plugin-readable-tailwind/blob/3843fe28fc9ef4820e9bcb03814a99beaed639e8/src/parsers/es.ts#L353
```tsx
const Example: Story = {
render: () => (
<div className="rounded-md h-48 w-48 relative after:h-8 after:w-8 after:absolute after:right-4 after:rotate-45">
Some content
</div>
)
}
```
closes #74

fix: lint `className` in render functions inside object

---

.cspell.json
README.md
src/rules/tailwind-multiline.ts
src/rules/tailwind-no-duplicate-classes.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts
src/tailwind/api/interface.ts
src/tailwind/v3/class-order.ts
src/tailwind/v4/class-order.ts
src/tailwind/v4/config.ts
src/utils/utils.ts

I have noticed that many users don’t configure the plugin correctly, in particular, the `lineBreakStyle` option, which often leads to avoidable issues.
With this PR, the rules can now detect potential misconfiguration by comparing the differences of the input string and the configured `lineBreakStyle` or `indent` options and prepends a warning if something doesn't match.

refactor: detect potential misconfiguration

---

src/parsers/es.ts
src/parsers/html.ts
src/parsers/svelte.ts
src/parsers/vue.ts
src/rules/tailwind-no-duplicate-classes.ts
src/types/ast.ts
src/utils/utils.ts

Another fix for #81. Normal ES literals also lack the `\r` character in the node content when processed via the vue eslint parser.
See: https://github.com/schoero/eslint-plugin-readable-tailwind/pull/82

fix: carriage return in es literals when processed via vue parser

---

CHANGELOG.md
package-lock.json
package.json
src/rules/tailwind-multiline.ts
src/rules/tailwind-no-duplicate-classes.ts
src/rules/tailwind-no-unnecessary-whitespace.ts
src/rules/tailwind-sort-classes.ts

Fixes an issue where the autofixed classes would contain unnecessarily escaped quotes when the class was in a template element after an interpolated template element:
```diff
const Test = (isActive: boolean) => (
<span
class={`
${isActive ? "text-red-500!" : ""}
-       group-[[data-state=\"open\"]]/collapsible:text-red-500
+       group-[[data-state="open"]]/collapsible:text-red-500
`}
>
Test
</span>
);
```

fix: unnecessarily escaped quotes

---

src/rules/tailwind-no-duplicate-classes.test.ts
src/rules/tailwind-no-duplicate-classes.ts
src/utils/utils.ts
tests/e2e/commonjs/test.test.ts
tests/e2e/esm/test.test.ts

Now reports errors in [`no-duplicate-classes`](https://github.com/schoero/eslint-plugin-readable-tailwind/blob/main/docs/rules/no-duplicate-classes.md) rule for each duplicate class instead of the whole class string.
```tsx
// Before:
<div class="grid grid" />;
~~~~~~~~~
// After:
<div class="grid grid" />;
~~~~
```

refactor: report error for each duplicate instead of the whole string

---

README.md
docs/rules/no-restricted-classes.md
src/configs/config.ts
src/rules/tailwind-no-restricted-classes.test.ts
src/rules/tailwind-no-restricted-classes.ts
tests/utils.ts

New rule to disallow tailwindcss classes
```tsx
// ❌ BAD: disallow the use of the child variants with option `{ restrict: ["^\\*+:.*"] }`
<div class="rounded *:mx-0" />;
//                  ~~~~~~
```
```tsx
// ❌ BAD: disallow the use of the important modifier `{ restrict: ["^.*!$"] }`
<div class="rounded p-4!" />;
//                  ~~~~
```

feat: no-restricted-classes

---

.cspell.json
README.md
docs/parsers/astro.md
package-lock.json
package.json
src/options/default-options.ts
src/parsers/jsx.test.ts
src/parsers/jsx.ts
src/utils/rule.ts
tests/utils.ts

Add support for the [`class:list` syntactic sugar](https://docs.astro.build/en/reference/directives-reference/#classlist) in astro.
```astro
```
closes #102

feat: add support for astro syntactic sugar

---

README.md
docs/rules/enforce-consistent-variable-syntax.md
src/configs/config.ts
src/rules/enforce-consistent-variable-syntax.test.ts
src/rules/enforce-consistent-variable-syntax.ts
src/rules/no-duplicate-classes.ts
src/utils/utils.ts

Enforce consistent css variable syntax in tailwindcss class strings.
```tsx
// ❌ BAD: Incorrect css variable syntax with option `syntax: "parentheses"`
<div class="bg-[var(--primary)]" />;
```
```tsx
// ✅ GOOD: With option `syntax: "parentheses"`
<div class="bg-(--primary)" />;
```
```tsx
// ❌ BAD: Incorrect css variable syntax with option `syntax: "arbitrary"`
<div class="bg-(--primary)" />;
```
```tsx
// ✅ GOOD: With option `syntax: "arbitrary"`
<div class="bg-[var(--primary)]" />;
```

feat: new rule `enforce consistent variable syntax`

---

docs/rules/no-restricted-classes.md
src/rules/no-restricted-classes.test.ts
src/rules/no-restricted-classes.ts
src/utils/utils.ts
tests/utils/lint.ts

```ts
{ 
restrict: [{ 
pattern: "^(.*)-green-500$",
message: "use '$1-success' instead."
}]
}
```
```tsx
<div class="text-green-500" />;
//          ~~~~~~~~~~~~~~ use 'text-success' instead.
```
fixes: #127

feat: no-restricted-classes rule to support custom error messages

---

src/parsers/es.ts
src/utils/matchers.test.ts
src/utils/matchers.ts

fixes: #125
```ts
const classes = () => {
const somethingElse = "no longer getting linted";
}
```

fix: prevent variable matchers from crossing arrow function boundaries

---

src/rules/sort-classes.test.ts
src/rules/sort-classes.ts

Fixes the "improved" sorting order, when an unregistered class with a variant was available among classes without variants.
Basically the classes without prefixes should always come first.
```ts
// before
```
```ts
// after
```

fix: improved sorting order with unregistered class with variant

---

docs/rules/no-restricted-classes.md
src/rules/no-restricted-classes.test.ts
src/rules/no-restricted-classes.ts

Adds a customizable autofix option to the `no-restricted-classes` rule:
```json
{
"restrict": [{
"fix": "$1$2-success$3",
"message": "Restricted class: Use '$1$2-success$3' instead.",
"pattern": "^([a-zA-Z0-9:/_-]*:)?(text|bg)-green-500(\\/[0-9]{1,3})?$"
}]
}
```
```jsx
// before
// after
```

feat: add autofix to `no-restricted-classes`

---

README.md
docs/api/defaults.md
docs/parsers/angular.md
docs/parsers/astro.md
docs/parsers/html.md
docs/parsers/javascript.md
docs/parsers/jsx.md
docs/parsers/svelte.md
docs/parsers/tsx.md
docs/parsers/typescript.md
docs/parsers/vue.md
docs/rules/enforce-consistent-class-order.md
docs/rules/enforce-consistent-line-wrapping.md
docs/rules/no-unnecessary-whitespace.md
package.json
src/configs/config.ts
src/parsers/angular.test.ts
src/parsers/html.test.ts
src/parsers/jsx.test.ts
src/parsers/svelte.test.ts
src/parsers/vue.test.ts
src/rules/deprecated/multiline.ts
src/rules/deprecated/sort-classes.ts
src/rules/enforce-consistent-class-order.test.ts
src/rules/enforce-consistent-class-order.ts
src/rules/enforce-consistent-line-wrapping.test.ts
src/rules/enforce-consistent-line-wrapping.ts
src/rules/no-unnecessary-whitespace.ts
tests/e2e/commonjs/test.test.ts
tests/e2e/esm/test.test.ts

Rename rules to be more consistent
- better-tailwindcss/multiline -> better-tailwindcss/enforce-consistent-line-wrapping
- better-tailwindcss/sort-classes -> better-tailwindcss/enforce-consistent-class-order
The old rule names have been deprecated and will be removed with v4.0.0.

refactor: rename rules

---

README.md
docs/rules/enforce-consistent-important-position.md
src/rules/enforce-consistent-important-position.test.ts
src/rules/enforce-consistent-important-position.ts
src/tailwindcss/important-position.async.v3.ts
src/tailwindcss/important-position.async.v4.ts
src/tailwindcss/important-position.async.worker.v3.ts
src/tailwindcss/important-position.async.worker.v4.ts
src/tailwindcss/important-position.ts

```tsx
// ❌ BAD: with option { "position": "recommended" }
<div class="!text-red-500 hover:!bg-blue-500"></div>;
```
New rule `enforce-consistent-important-position`
```tsx
// ✅ GOOD: with option { "position": "recommended" }
<div class="text-red-500! hover:bg-blue-500!"></div>;
```
```tsx
// ❌ BAD: with option { "position": "legacy" }
<div class="text-red-500! hover:bg-blue-500!"></div>;
```
```tsx
// ✅ GOOD: with option { "position": "legacy" }
<div class="!text-red-500 hover:!bg-blue-500"></div>;
```
fixes #163

feat: new rule `enforce-consistent-important-position`

---

src/async-utils/resolvers.ts
src/async-utils/version.ts
src/rules/no-unregistered-classes.test.ts
src/tailwindcss/context.async.v4.ts
src/tailwindcss/custom-component-classes.async.v4.ts
src/tailwindcss/custom-component-classes.ts

- Fixes crash when importing css files via tsconfig path alias and [`detectComponentClasses`](https://github.com/schoero/eslint-plugin-better-tailwindcss/blob/main/docs/rules/no-unregistered-classes.md#detectcomponentclasses) enabled
- Fixes component classes not getting updated when inside an imported file

fix: component classes improvements

---

src/options/descriptions.ts

The rules currently allow extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in rules' schemas which currently allow them.

fix: disallow extra properties in rule options

---

src/rules/no-deprecated-classes.test.ts
src/rules/no-deprecated-classes.ts

Adds missing deprecations:
4.0
- `inset-shadow` -> `inset-shadow-sm`
4.1 
- `bg-left-top` -> `bg-top-left`
- `bg-left-bottom` -> `bg-bottom-left`
- `bg-right-top` -> `bg-top-right`
- `bg-right-bottom` -> `bg-bottom-right`
- `object-left-top` -> `object-top-left`
- `object-left-bottom` -> `object-bottom-left`
- `object-right-top` -> `object-top-right`
- `object-right-bottom` -> `object-bottom-right`

refactor: add missing deprecations

---

docs/rules/enforce-consistent-variable-syntax.md
src/rules/enforce-consistent-variable-syntax.test.ts
src/rules/enforce-consistent-variable-syntax.ts

Now supports Tailwind CSS v3 shorthands.  
```tsx
// ❌ BAD: Incorrect css variable syntax with option `syntax: "shorthand"`
<div class="bg-[var(--primary)]" />;
```
```tsx
// ✅ GOOD: With option `syntax: "shorthand"` in Tailwind CSS v4
<div class="bg-(--primary)" />;
```
```tsx
// ✅ GOOD: With option `syntax: "shorthand"` in Tailwind CSS v3
<div class="bg-[--primary]" />;
```
```tsx
// ❌ BAD: Incorrect css variable syntax with option `syntax: "variable"` in Tailwind CSS v4
<div class="bg-(--primary)" />;
```
```tsx
// ❌ BAD: Incorrect css variable syntax with option `syntax: "variable"` in Tailwind CSS v3
<div class="bg-[--primary]" />;
```
```tsx
// ✅ GOOD: With option `syntax: "arbitrary"`
<div class="bg-[var(--primary)]" />;
```

refactor: variable syntax tailwindcss3 shorthand

---

src/tailwindcss/conflicting-classes.async.worker.v3.ts

fix: error in no-conflicting-classes when used in tailwindcss 3

---

src/rules/enforce-shorthand-classes.test.ts
src/rules/enforce-shorthand-classes.ts

fix: differentiate shorthands for same classes with different variants

---

.cspell.json
package-lock.json
package.json
src/rules/no-unregistered-classes.test.ts

Add DaisyUI dev dependency.
Add V3 test covering `btn`, `btn-primary`, `btn-circle`, `btn-ghost`, `dropdown`, and `dropdown-hover`.
Add V4 test for the same.
Warning, V4 test is failing on `dropdown-hover`.
References: #179

test: add no-unregistered-classes test for DaisyUI classes

---

.vscode/settings.json
src/parsers/angular.test.ts
src/parsers/angular.ts

**Summary**
Fixes a TypeError in the Angular parser where `objectContent` can be `undefined` and `.slice` is called unguarded.
Adds defensive checks and safe fallbacks in `createLiteralByLiteralMapKey` so the rule bails out gracefully instead of crashing.
No behavioral change for valid inputs; only prevents executor failure on edge AST shapes.
**Problem**
Running ESLint with eslint-plugin-better-tailwindcss on Angular templates can crash with:
TypeError: Cannot read properties of undefined (reading 'slice')
Rule: better-tailwindcss/enforce-consistent-class-order (also reproducible on other rules reading class strings)
Root location:
File: parser for Angular templates
Function: createLiteralByLiteralMapKey
Line (approx.): `const currentStart = …

Angular parser: prevent crash when objectContent is undefined in createLiteralByLiteralMapKey

---

src/options/callees/tv.ts

When using Tailwind Variants `compoundVariants` that only apply to certain slots, the class string is not detected. 
In this example the className string in the compoundVariant for the `h1` slot is not linted. 
To reproduce, see this codesandbox https://codesandbox.io/p/devbox/h7kpvk and run `pnpm run lint --fix`
```
const tvClasses = tv({
slots: {
h1: `
bg-red-500 font-bold
hover:bg-blue-700
active:font-bold
`,
},
variants: {
hasError: {
true: "bg-green-500",
},
isSelected: {
true: "border-yellow-500",
},
isWorking: {
true: `
bg-red-500 font-bold
hover:bg-blue-100
active:font-bold
`,
},
},
compoundVariants: [
{
isSelected: true,
hasError: true,
className: {
h1: "bg-red-500 font-bold hover:bg-blue-100 active:font-bold",
},
},
],
});
```
The fix adds `.*` to the end of the compoundVariants …

fix: not detecting compoundVariants using slots from Tailwind Variants
